# nabbed from https://github.com/YoshiCrafter29/CodenameEngine
# by YoshiCrafter29

name: Linux Build
on:
  push:
    branches: [legacy, hybrid, rewrite]
  pull_request:
    branches: [legacy, hybrid, rewrite]
jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:

    - name: Pulling the new commit
      uses: actions/checkout@v2

    - name: Setting up Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Restore existing build cache for faster compilation
      uses: actions/cache@v3
      with:
        key: cache-build-linux
        path: |
          .haxelib/
          export/release/linux/haxe/
          export/release/linux/obj/
        restore-keys: |
          cache-build-linux

    - name: Installing/Updating libraries
      run: |
        haxelib setup ~/haxelib
        haxelib install hxcpp
        haxelib install lime
        haxelib install openfl
        haxelib install flixel
        haxelib install flixel-addons
        haxelib install flixel-ui
        haxelib install hscript
        haxelib install flixel-tools
        haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
        haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons

    - name: Building the game
      run: haxelib run lime build linux

    - name: Uploading artifact (entire build)
      uses: actions/upload-artifact@v2
      with:
        name: Forever-Engine
        path: export/release/linux/bin

    - name: Uploading artifact (executable)
      uses: actions/upload-artifact@v2
      with:
        name: Update-Linux
        path: export/release/linux/bin/Forever-Engine
